sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  COMMIT: ${TRAVIS_COMMIT::8}
  MAIN_REPO: https://github.com/testdrivenio/testdriven-app-2.5.git
  USERS: test-driven-users
  USERS_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users
  USERS_DB: test-driven-users_db
  USERS_DB_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users/project/db
  CLIENT: test-driven-client
  CLIENT_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/client
  SWAGGER: test-driven-swagger
  SWAGGER_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/swagger
  EXERCISES: test-driven-exercises
  EXERCISES_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/exercises
  EXERCISES_DB: test-driven-exercises_db
  EXERCISES_DB_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/exercises/project/db
  SECRET_KEY: my_precious

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - export REACT_APP_EXERCISES_SERVICE_URL=http://127.0.0.1
  - export REACT_APP_API_GATEWAY_URL=https://chxkdoq5n8.execute-api.us-west-1.amazonaws.com/v1/execute
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then export LOAD_BALANCER_DNS_NAME=http://testdriven-staging-alb-741461415.us-west-1.elb.amazonaws.co; fi
  - if [[ "$TRAVIS_BRANCH" == "production" ]]; then export LOAD_BALANCER_DNS_NAME=http://testdriven-production-alb-770072310.us-west-1.elb.amazonaws.com; fi
  - npm install

script:
  - bash test-ci.sh $TRAVIS_BRANCH

after_success:
  - bash ./docker-push.sh
  - bash ./docker-deploy-stage.sh
  - bash ./docker-deploy-prod.sh
